Update ausserhalb-des-studiums.md
fsi-hska/iwi-website pull request #11
Opened 2020-09-06 11:43 UTC by blackcatfighter

2020-09-06 11:44 UTC, blackcatfighter commented
Infos eingefügt

2020-09-08 09:41 UTC, Wekra requested changes
Add some general feedback regarding the content.

2020-09-08 09:41 UTC, Wekra commented on content/faq/ausserhalb-des-studiums.md
> +Auch die Günther-Klotz-Anlage eignet sich durch die Grünanlage als Freizeit- und Erholungsort. Das bekannte „Fest“ findet jährlich im Sommer auf der „Klotze“ statt.
"[...] auf der Klotze" or rather "[...] in der Klotze" ? 🤔

2020-09-08 09:41 UTC, Wekra commented on content/faq/ausserhalb-des-studiums.md
> +Filmpalast, Universum, Schauburg, Die Kurbel
'Die Kurbel' is [insolvent as of 2018](https://ka.stadtwiki.net/Die_Kurbel).

2020-09-29 23:38 UTC, Wekra commented
Resolved in #16 and will therefore be closed.

2020-09-29 23:39 UTC, closed without merging

2020-09-29 23:39 UTC, Wekra commented
@blackcatfighter do you want to keep the patch-branch open?